### ISSUE TITLE
Album art doesn't download at 500 x 500 size

### ISSUE THREAD

**Issue by zchlm** [brkastner/SDownload#134]
SDownload doesn't download the 500 x 500 size of the album art, instead it grabs the 120 x 120 album art. Unsure if this is an issue or a possible enhancement.

**Comment by brkastner** [comment]
I was not aware that there was an album art size greater than 120 x 120. I don't currently have the time to continue working on SDownload but hopefully this fall I'll get to this. I'll add it to the list of things to add.
