### ISSUE TITLE
Won't download tracks with forward slashes in the title

### ISSUE THREAD

**Issue by psyrendust** [brkastner/SDownload#3]
If the track name has a forward slash in the title, sdownloader will treat the slashes as a folder name versus part of the file name. Is there a way to change forward slashes to `-`, `_`, or a space when constructing the file name?

Here is a page that has a few examples of what I'm referring to.
https://soundcloud.com/djmarkfarina

```
There was an error saving to the file '/var/folders/cr/1_rcyq6978x7bx_203km5d7w0000gn/T/Mushroom Jazz 18 mix tape side 1   2/17/95.jpg':The file “95.jpg” doesn’t exist.
```

**Comment by brkastner** [comment]
By the looks of the error message I'm assuming you are on a Mac?

Mac support is very limited at the moment as I do not have access to one to make the necessary changes anymore. However, by the end of the year that should change.

On a more related note, I'll make the necessary changes to fix this in the next major release I'm working on for PC. Once I have access to a Mac I'll fix it for that as well.

Brennan

**Comment by psyrendust** [comment]
Thanks for the reply. Yes I the error is from a Mac. If you have an idea of
what the fix is I can make the changes in a fork or branch and compile it
myself using Xcode. I'd be more thank happy to help in testing this for
you.

---

Larry Gordon
Director of Digital Development
John McNeil Studio
720 Channing Way
Berkeley, Ca 94710
o: 510-526-7100
c: 415-312-0361
larry@johnmcneilstudio.com

On Oct 7, 2013, at 3:34 PM, Brennan Kastner notifications@github.com
wrote:

By the looks of the error message I'm assuming you are on a Mac?

Mac support is very limited at the moment as I do not have access to one to
make the necessary changes anymore. However, by the end of the year that
should change.

On a more related note, I'll make the necessary changes to fix this in the
next major release I'm working on for PC. Once I have access to a Mac I'll
fix it for that as well.

Brennan

—
Reply to this email directly or view it on
GitHubhttps://github.com/brkastner/SDownload/issues/3#issuecomment-25851272
.

**Comment by brkastner** [comment]
I was actually going to use your suggestion and just use '_' as a replacement for any '/' found in the title.

The code behind the Mac release of SDownload could really use some work though so I was planning on just starting from scratch in the next release like I did for PC. The source isn't actually on my machine anymore but my buddy's who I was originally borrowing a Mac from to make it. I could've sworn I backed it up to an online private repository before I lost access to the Mac but I can't find it for the life of me. Let me see if I can get a hold of it for you so you can make the necessary changes!

Thanks for being interested in helping out!

**Comment by brkastner** [comment]
Closing the issue as it is fixed in the PC version, the Mac version will more than likely have a separate issue tracker once it is live.
